---
# tasks file for docker
- name: Log on which Linux distro Docker is going to be installed
  debug:
    msg: "The distro is: {{ ansible_distribution }} "

- name: Add Docker yum repo
  yum_repository:
    name: docker-ce
    description: "Docker CE repo"
    baseurl: "https://download.docker.com/linux/centos/7/$basearch/stable"
    gpgkey: "https://download.docker.com/linux/centos/gpg"
    state: present
  become: true

- name: Install Docker rpm package
  yum:
    name: docker-ce
    state: latest
  become: true

- name: add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: true
  become: true
